### PR TITLE
KubeEdge v1.14.2 killercoda Scenerio

### PR DESCRIPTION
**Pull request by sarthaksarthak9**
<H1> Explanation</H1>

Deployed KubeEdge v1.24.2 on Kubernetes v1.24.0 cluster wiith the integration of example in the examples repo of KubeEdge and show it on the user interactive platform Killercoda.

<H1>Related issue</H1>

Closses #8 

<H1>Milestone of this PR</H1>

<H1>What type of PR is this</H1>

/kind api-change<br>
/kind feature

### CODE REVIEW

**Comment by sarthaksarthak9** [comment]
@fisherxu  pls check this out!!

**Comment by sarthaksarthak9** [comment]
@sids-b could you pls check this out!!

**Comment by fisherxu** [comment]
@sarthaksarthak9 I've created an dev branch dev-1.14, could you please raise this PR to dev-1.14? We can have some fixs and then merge to master, thanks

**Comment by sarthaksarthak9** [comment]
> @sarthaksarthak9 I've created an dev branch dev-1.14, could you please raise this PR to dev-1.14? We can have some fixs and then merge to master, thanks

Done!! @fisherxu

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Comment by sarthaksarthak9** [comment]
@fisherxu something else I need to do?

**Pull request merged**
